# lightning.pytorch==2.1.0
model:
  input_size: 230 # vocab_size*seq_len
  hidden_size: 1000
  n_hidden: 1
  dropout: 0.5
  lr: 0.001
data:
  class_path: lit_modules.data_modules.GenomeDataModule
  init_args:
    data_file: ../data/reference/hg38.fa
    chr: chr1
    num_workers: 0
    batch_size: 128
