# lightning.pytorch==2.1.0
trainer:
  callbacks:
    class_path: BedWriter
    init_args:
      output_dir: output
      write_interval: epoch
      chr_name: chr1
      seq_length: 46
model:
  input_size: 230 # vocab_size*seq_len
  hidden_size: 250
  n_hidden: 1
  dropout: 0.5
data:
  class_path: lit_modules.data_modules.GenomeDataModule
  init_args:
    data_file: ../data/reference/hg38.fa
    num_workers: 0
    batch_size: 128
    chr_name: chr1
    seq_length: 46
