# lightning.pytorch==2.1.0
trainer:
  max_epochs: 40
model:
  class_path: lit_modules.modules.RegressionModule
  init_args:
    basemodel:
      class_path: models.models.TransformerModel
      init_args:
        seq_length: 46
        ntoken: 5
        d_model: 32
        nhead: 8
        nlayers: 2
        nhid: 512
        dropout: 0.5
    lr: 0.0001
data:
  class_path: lit_modules.data_modules.NumericDataModule
  init_args:
    data_path: data/TB000208a
    decoy_path: data/decoys_500K
    genomic_reference_file: ../data/reference/hg38.fa
    decoy_mul: 0
    sequence_length: 46
    train_test_split: 0.8
    batch_size: 64
    log_transform: log
    one_hot: False
